name: Docker Image CI for GHCR

on:
  push

jobs: 
  test:
      runs-on: ubuntu-latest
      container:
        image: ubuntu:latest
      steps:
        - uses: actions/checkout@v3
        - run: |
            echo ${{ github.workspace }}
            echo $GITHUB_WORKSPACE
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build and push the image
        run:  ./mvnw -s $GITHUB_WORKSPACE/settings.xml -X clean install jib:dockerBuild

#         ./mvnw -X clean install jib:dockerBuild
#          docker push 
         
